### ISSUE TITLE
Thanks for this resource + tldr-pages usage

### ISSUE THREAD

**Issue by waldyrious** [keith/xcode-man-pages#5]
Hi there! Just dropping a note of appreciation for providing this resource, and letting you know that the [tldr-pages project](https://tldr.sh) has decided to adopt your site as the default source of manpage links for all XCode-bundled commands. Relevant links:
- [Issue with the discussion and approval of this change](https://github.com/tldr-pages/tldr/issues/11963)
- [PR adding the recommendation to the style guide](https://github.com/tldr-pages/tldr/pull/12097)
- [PR mass-replacing all manpage links to point to your site](https://github.com/tldr-pages/tldr/pull/12168)

(Btw, in case you see increased traffic to your site in the near future, this may be part of the reason.)

Cheers! Feel free to close the issue when you read it, or leave it open so others can express their appreciation as well! :D

**Comment by keith** [comment]
Nice! Thanks for the kind words. I'm glad this resource is useful for other folks as well!
